[[redirects]]
  from = "/"
  to = "/apps/landing/dist"

[[redirects]]
  from = "/challenger/1"
  to = "/apps/challenger-1/dist"

[[redirects]]
  from = "/challenger/2"
  to = "/apps/challenger-2/dist"
